groups:
  - name: example
    rules:
      - alert: service_down
        expr: up == 0
        for: 10s
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 seconds."

      - alert: site_down
        expr: probe_success < 1
        for: 10s
        labels:
          severity: page
        annotations:
          summary: "Site Down: {{$labels.instance}}"
          description: "Site Down: {{$labels.instance}} for more than 10 seconds"

      - alert: sudden_traffic_spike
        expr: rate(http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Sudden traffic spike detected for {{ $labels.instance }}"
          description: "Traffic has spiked to over 1000 requests per second for the last 5 minutes."

      - alert: blackbox_ssl_certificate_will_expire_soon
        expr: 0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 3
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
          description: "SSL certificate expires in less than 3 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: high_cpu_usage
        expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) / sum(rate(node_cpu_seconds_total[5m])) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on instance {{ $labels.instance }}"
          description: "CPU usage has been above 80% for the last 5 minutes."

      - alert: high_memory_usage
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage detected on instance {{ $labels.instance }}"
          description: "Available memory is below 20% for the last 5 minutes."

      - alert: low_disk_space
        expr: node_filesystem_free_bytes / node_filesystem_size_bytes * 100 < 15
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on instance {{ $labels.instance }}"
          description: "Disk space is below 15% for the last 10 minutes."

      - alert: container_stopped
        expr: time() - container_last_seen > 60
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} has stopped"
          description: "Container {{ $labels.name }} has not been seen for more than 10 minutes."
